config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}
  root 'welcome#home'

  post '/set_locale/wow', to: 'users#set_locale', as: :set_user_locale
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :set_locale

  def set_locale
    I18n.locale = user_signed_in? ? current_user.locale.to_sym : 
    	I18n.default_locale
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
end 

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def set_locale
		new_locale = params[:locale]
		if ['es', 'en'].include?(new_locale)
			current_user.update_attributes(locale: new_locale)
			I18n.locale = new_locale.to_sym
			flash[:success] = t('locale_changed')
			redirect_to :back
		else
			flash[:error] = t('locale_changed_error')
			redirect_to :back
		end
	end
end

app/controllers/welcome_controller.rb
# Welcome controller. Serves as the user's dashboard
class WelcomeController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_nav_bar.html.slim
div class="navBtn"
	| +
nav
  -if user_signed_in?
    = link_to t('edit_user'), edit_user_registration_path
    = link_to('Logout', destroy_user_session_path, method: :delete) 
    div class="row"
      div class="col-md-1"
        = link_to_if current_user.locale != 'en', image_tag("USA-flag-icon.png", height: '16', width: '22'), set_user_locale_path(locale: 'en'), method: :post, class: "locale_active"
      div class="col-md-1"
        = link_to_if current_user.locale != 'es', image_tag("mexico-flag-icon.png", height: '16', width: '22'), set_user_locale_path(locale: 'es'), method: :post, class: "locale_active"
  -else
    = link_to t('login'), new_user_session_path    
    = link_to t('signup'), new_user_registration_path

app/views/layouts/_sweet_alerts.html.erb
<!-- Flash bootstrap element -->
<% unless flash.empty? %>
  <% [:success, :info, :danger, :error].each do |condition| %>
    <% if flash[condition] %>
    <script>
      $(window).load(function(){
        $(document).ready(function () {
            swal(
              { 
                title: "<%= t(condition) %>", 
                text: "<%= flash[condition] %>", 
                type: "<%= condition %>" 
              }
            );
        });
      });              
    </script> 
    <% end %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bedrock</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,700' rel='stylesheet' type='text/css'>
</head>
<body>

	<div class="container">
  
	  <div class="overlay"></div>

	  <header>

	  	<%= render 'layouts/nav_bar' %>

	  </header>
	  
	  <div class="main">
	  	<div class="row">
				<%= render 'layouts/sweet_alerts' %>
			  <div class="col-md-12">
			  	<% if notice %>
					  <p class="alert alert-success"><%= notice %></p>
					<% end %>
					<% if alert %>
					  <p class="alert alert-danger"><%= alert %></p>
					<% end %>
			  	<%= yield %>
			  </div>
			</div>
	  </div>
	  
	</div>

</body>
</html>